### ISSUE TITLE
ERR display

### ISSUE THREAD

**Issue by IrealiTY** [Ihellmasker/FFXIVParserSkin#1]
While ACT itself displays everything normally the overlay shows ERR on Encounter, ACC, DPS etc.

OverlayPlugin is 0.3.3.11
![image](https://user-images.githubusercontent.com/1223686/27004639-a534a998-4e0c-11e7-9a6a-a7b751da347b.png)

**Comment by Ihellmasker** [comment]
Try going into the settings and resetting it to default. Possibly somethings gone wrong with them.

**Comment by IrealiTY** [comment]
That actually did the trick, could have sword I rested them before. Cheers man!

**Comment by Ihellmasker** [comment]
Great! Glad that worked, was worried I broke something D:

Kinda surprised to see someone else using it c.c.

**Comment by IrealiTY** [comment]
Ha! It's my to go overlay since a few month(s?)  Just needs automatic Discord posts after an encounter- might fork later for that...

**Comment by Ihellmasker** [comment]
I was thinking about putting automatic posting in when I've rebuild the settings slightly because I want to add configuration options to the auto posting, such as min/ax party size, min dps, min time, to stop it being spammy

**Comment by IrealiTY** [comment]
Ah yeah, that sounds better, could end up spammy.
