### ISSUE TITLE
BrowserConsole: Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by ghost** [Ihellmasker/FFXIVParserSkin#2]
I'm getting some pretty consistent spam in console:

Info: Mini Parse: BrowserConsole: Uncaught ReferenceError: $ is not defined 
(Source: https://ihellmasker.github.io/FFXIVParserSkin/overlay/js/act.js?v=100, Line: 15)

Line 15: if ($("#updateNotes").is(":visible")) $("#updateNotes").hide();

**Comment by Ihellmasker** [comment]
Hmm, I've got no idea honestly. I'm not seeing the error at all. Have to tried reloading the overlay. $ not being defined means JQuery isn't loading, which makes no sense really.

**Comment by ghost** [comment]
I think it might have something to do with opening the settings, and my browser being laggy. The window doesnt immediately pop up, or the settings dont populate.

Let's blame my machine on this one, thanks.
