### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ghost** [Ihellmasker/FFXIVParserSkin#7]
Since there is no LICENSE added to this project [its legally prohibited to do any changes](https://choosealicense.com/no-permission/) I really like your project and would like to continue it. Could you please add a license to this repo?

**Comment by Ihellmasker** [comment]
Done :)

If you're interested in maintaining and updating it we can probably discuss giving you this repo, or at least do pull requests to it.

**Comment by ghost** [comment]
Nice, thanks for the quick response! I am okay to just have a fork, honestly.
